### ISSUE TITLE
Diff mode Merged shows result only partially

### ISSUE THREAD

**Issue by vendeeglobe** [JBlond/php-diff#90] opened 2021-02-11 13:33 UTC
After implementing the Merged mode a few days ago using php-diff 2.3.1, it seems that the HTML Merged mode shows the diff only partially in comparison to Unified or SideBySide.

Example:
Unified
![diff_unified](https://user-images.githubusercontent.com/54716082/107642610-65cf7400-6c75-11eb-89c0-a0f64effd8db.png)

Merged
![diff_merged](https://user-images.githubusercontent.com/54716082/107642644-6f58dc00-6c75-11eb-8d00-55d6b9d0e2e5.png)

Example text:
[version_a.txt](https://github.com/JBlond/php-diff/files/5965450/version_a.txt)
[version_b.txt](https://github.com/JBlond/php-diff/files/5965462/version_b.txt)

**Comment by DigiLive** [comment] 2021-02-11 14:02
Can you mention the lines you are referring to?
HTML merged only marks inline differences and added blocks text.
Blocks of texts which are removed at version 2, are marked in line column of the table:
![afbeelding](https://user-images.githubusercontent.com/7613487/107646356-2a837400-6c7a-11eb-91e1-18c29e904047.png)

**Comment by vendeeglobe** [comment] 2021-02-11 15:49
Ignores changes in line 
19 to 21
70 to 86
99 -  not shown at all, not like in your example above

![diff_sidebyside](https://user-images.githubusercontent.com/54716082/107659934-ffa01c80-6c87-11eb-8ded-c09c56056523.png)

Example: (enabled diff for guests temporarily)
https://wackowiki.org/doc/Doc/English/Themes/diff?a=4227&b=0&diffmode=5

**Comment by DigiLive** [comment] 2021-02-11 16:04
Which options did you provide to the Diff class?

**Comment by vendeeglobe** [comment] 2021-02-11 16:45
No options, only default. Should I set particular options for Merged?

https://github.com/WackoWiki/wackowiki/blob/master/wacko/handler/page/diff.php#L352

**Comment by vendeeglobe** [comment] 2021-02-12 20:27
I forgot to mention that I use PHP 8.0.

Found this in the error log with varying array keys:
PHP Warning:  Undefined array key 5 in /lib/php-diff/Diff/Renderer/Html/Merged.php on line 217

**Comment by DigiLive** [comment] 2021-02-12 20:54
I didn't test with php 8, bit I'm still suprised by it.
I'll take a look into it soon.

Thank you for testing and feedback.

**Comment by DigiLive** [comment] 2021-02-13 14:20
> 
> 
> I forgot to mention that I use PHP 8.0.
> 
> Found this in the error log with varying array keys:
> PHP Warning: Undefined array key 5 in /lib/php-diff/Diff/Renderer/Html/Merged.php on line 217
> 
> `preg_match_all('/\x0.*?\x1/', $changes['changed']['lines'][$lineNo], $addedParts, PREG_PATTERN_ORDER);`

Something is incorrect with your error description or file. See below lines.
https://github.com/JBlond/php-diff/blob/9830fe059c020d4d72936ef171d983df3d379d7e/lib/jblond/Diff/Renderer/Html/Merged.php#L216-L218

Also the script doesn't throw a warning or error at my local server, using php v8.0.2.

**Comment by vendeeglobe** [comment] 2021-02-13 15:00
I patched away the table header therfore the different line number.
https://github.com/WackoWiki/wackowiki/blob/master/wacko/lib/php-diff/Diff/Renderer/Html/Merged.php#L217

The error messages are from the server log and do probably not belong to the posted example. I turn error reporting on again after posting the issue.

**Comment by DigiLive** [comment] 2021-02-13 15:07
I've created a new issue for it since it seems unrelated to the original report.
Please continue the discussion about the thrown warning over there.

Also you don't have to patch the renderer. You can create your own or extend an included one.
See https://github.com/JBlond/php-diff/wiki/3.-Custom-Renderer

**Comment by DigiLive** [comment] 2021-02-16 13:38
> Ignores changes in line
> 19 to 21
> 70 to 86
> 99 - not shown at all, not like in your example above

---
19 to 21: **Bug confirmed.** Will create a PR for it soon.
70-86: Marked as inserted (see below).
99: Table header marked as deleted at version 1 (see below).

![afbeelding](https://user-images.githubusercontent.com/7613487/108069977-47e28480-7064-11eb-8a80-6a8005df0bf9.png)

**Closed** 2021-03-27 13:34 UTC
Labels: bug, confirmed

**Comment by DigiLive** [comment] 2021-03-27 14:50
Don't forget to clear you browsers cache to pull in the newest css files.

**Comment by vendeeglobe** [comment] 2021-03-27 17:13
Already merged and Browser cache has been purged.
